[package]
name = "ppm-models"
version = "0.4.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
ed25519-dalek = { version = "2.1.1", features = ["serde"] }
serde = { version = "1.0.209", features = ["derive"] }
serde_json = "1.0.127"
tsify-next = { version = "0.5.4", features = ["js"] }
wasm-bindgen = "0.2.93"
x25519-dalek = { version = "2.0.1", features = ["serde"] }
