[package]
name = "ppm-models"
version = "0.1.0"
edition = "2021"

[dependencies]
ed25519-dalek = {version = "2.1.1", features = ["serde"]}
serde = {version = "1.0.204", features = ["derive"]}
serde_json = "1.0.122"
x25519-dalek = {version = "2.0.1", features = ["serde"]}
