[package]
name = "ppm-models"
version = "0.6.3"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
blake3 = "1.5.4"
chrono = { version = "0.4.38", features = ["serde"] }
ed25519-dalek = { version = "2.1.1", features = ["serde"] }
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
tsify-next = { version = "0.5.4", features = ["js"] }
uuid = { version = "1.10.0", features = ["v4"] }
wasm-bindgen = "0.2.93"
x25519-dalek = { version = "2.0.1", features = ["serde"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.2", features = ["js"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
sqlx = { version = "0.8.2", features = ["chrono", "sqlite"] }
